baseURL: /
title: Sailor Hat for Raspberry Pi
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
enableGitInfo: true
taxonomies:
  tag: tags
  category: categories
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Hat Labs Oy
  privacy_policy: ''
  version_menu: Releases
  archived_version: false
  version: '1.0'
  url_latest_version: 'https://docs.hatlabs.fi/sh-rpi/'
  github_repo: 'https://github.com/hatlabs/sh-rpi'
  github_project_repo: 'https://github.com/hatlabs/SH-RPi-hardware'
  github_branch: main
  gcs_engine_id: a31868f3e68674aa2
  algolia_docsearch: false
  offlineSearch: false
  prism_syntax_highlighting: false
  ui:
    breadcrumb_disable: false
    footer_about_disable: false
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_menu_compact: false
    sidebar_search_disable: false
    feedback:
      enable: false
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/hatlabs/sh-rpi/issues/new">tell us how we
        can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/hatlabs/sh-rpi/issues/new">tell us how we
        can improve</a>.
    readingtime:
      enable: false
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
services:
  googleAnalytics:
    id: G-F3KDPEBJEF
languages:
  en:
    title: Sailor Hat for Raspberry Pi
    description: A smart power management hat for Raspberry Pi
    languageName: English
    weight: 1
    time_format_default: 2006-01-02
    time_format_blog: 2006-01-02
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    - print
    - RSS
module:
  hugoVersion:
    extended: true
    min: 0.75.0
  imports:
    - path: github.com/google/docsy
      disable: false
    - path: github.com/google/docsy/dependencies
      disable: false
menu:
  main:
    - name: Main Site
      weight: 10
      url: 'https://hatlabs.fi'
    - name: Shop
      weight: 20
      url: 'https://shop.hatlabs.fi'
    - name: Docs
      weight: 30
      url: 'https://docs.hatlabs.fi'
    - name: Discussion
      weight: 40
      url: 'https://github.com/hatlabs/discussions/discussions'
    - name: Contact
      weight: 50
      url: 'https://hatlabs.fi/contact'
